import type { GoogleCalendar } from "../client";
import type {
  DeleteEventsInput,
  GetEventsInput,
  GetEventsResponse,
  ImportEventsInput,
  ImportEventsResponse,
  InsertEventsInput,
  InsertEventsResponse,
  InstancesEventsInput,
  InstancesEventsResponse,
  ListEventsInput,
  ListEventsResponse,
  MoveEventsInput,
  MoveEventsResponse,
  PatchEventsInput,
  PatchEventsResponse,
  QuickAddEventsInput,
  QuickAddEventsResponse,
  UpdateEventsInput,
  UpdateEventsResponse,
  WatchEventsInput,
  WatchEventsResponse,
} from "./interfaces";

export class Events {
  constructor(private readonly client: GoogleCalendar) {}

  async list(params: ListEventsInput): Promise<ListEventsResponse> {
    return this.client.get<ListEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        eventTypes: params.eventTypes,
        iCalUID: params.iCalUID,
        maxAttendees: params.maxAttendees,
        maxResults: params.maxResults,
        orderBy: params.orderBy,
        pageToken: params.pageToken,
        privateExtendedProperty: params.privateExtendedProperty,
        q: params.q,
        sharedExtendedProperty: params.sharedExtendedProperty,
        showDeleted: params.showDeleted,
        showHiddenInvitations: params.showHiddenInvitations,
        singleEvents: params.singleEvents,
        syncToken: params.syncToken,
        timeMax: params.timeMax,
        timeMin: params.timeMin,
        timeZone: params.timeZone,
        updatedMin: params.updatedMin,
      },
      params.signal,
    );
  }

  async insert(params: InsertEventsInput): Promise<InsertEventsResponse> {
    return this.client.post<InsertEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        conferenceDataVersion: params.conferenceDataVersion,
        maxAttendees: params.maxAttendees,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
        supportsAttachments: params.supportsAttachments,
      },
      {
        anyoneCanAddSelf: params.anyoneCanAddSelf,
        attachments: params.attachments,
        attendees: params.attendees,
        attendeesOmitted: params.attendeesOmitted,
        colorId: params.colorId,
        conferenceData: params.conferenceData,
        description: params.description,
        end: params.end,
        endTimeUnspecified: params.endTimeUnspecified,
        eventType: params.eventType,
        extendedProperties: params.extendedProperties,
        focusTimeProperties: params.focusTimeProperties,
        gadget: params.gadget,
        guestsCanInviteOthers: params.guestsCanInviteOthers,
        guestsCanModify: params.guestsCanModify,
        guestsCanSeeOtherGuests: params.guestsCanSeeOtherGuests,
        iCalUID: params.iCalUID,
        id: params.id,
        location: params.location,
        originalStartTime: params.originalStartTime,
        outOfOfficeProperties: params.outOfOfficeProperties,
        privateCopy: params.privateCopy,
        recurrence: params.recurrence,
        recurringEventId: params.recurringEventId,
        reminders: params.reminders,
        sequence: params.sequence,
        source: params.source,
        start: params.start,
        status: params.status,
        summary: params.summary,
        transparency: params.transparency,
        visibility: params.visibility,
        workingLocationProperties: params.workingLocationProperties,
      },
      params.signal,
    );
  }

  async import(params: ImportEventsInput): Promise<ImportEventsResponse> {
    return this.client.post<ImportEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/import`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        conferenceDataVersion: params.conferenceDataVersion,
        supportsAttachments: params.supportsAttachments,
      },
      {
        anyoneCanAddSelf: params.anyoneCanAddSelf,
        attachments: params.attachments,
        attendees: params.attendees,
        attendeesOmitted: params.attendeesOmitted,
        colorId: params.colorId,
        conferenceData: params.conferenceData,
        description: params.description,
        end: params.end,
        endTimeUnspecified: params.endTimeUnspecified,
        eventType: params.eventType,
        extendedProperties: params.extendedProperties,
        focusTimeProperties: params.focusTimeProperties,
        gadget: params.gadget,
        guestsCanInviteOthers: params.guestsCanInviteOthers,
        guestsCanModify: params.guestsCanModify,
        guestsCanSeeOtherGuests: params.guestsCanSeeOtherGuests,
        iCalUID: params.iCalUID,
        id: params.id,
        location: params.location,
        originalStartTime: params.originalStartTime,
        outOfOfficeProperties: params.outOfOfficeProperties,
        privateCopy: params.privateCopy,
        recurrence: params.recurrence,
        recurringEventId: params.recurringEventId,
        reminders: params.reminders,
        sequence: params.sequence,
        source: params.source,
        start: params.start,
        status: params.status,
        summary: params.summary,
        transparency: params.transparency,
        visibility: params.visibility,
        workingLocationProperties: params.workingLocationProperties,
      },
      params.signal,
    );
  }

  async quickAdd(params: QuickAddEventsInput): Promise<QuickAddEventsResponse> {
    return this.client.post<QuickAddEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/quickAdd`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        text: params.text,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
      },
      undefined,
      params.signal,
    );
  }

  async watch(params: WatchEventsInput): Promise<WatchEventsResponse> {
    return this.client.post<WatchEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/watch`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        eventTypes: params.eventTypes,
        iCalUID: params.iCalUID,
        maxAttendees: params.maxAttendees,
        maxResults: params.maxResults,
        orderBy: params.orderBy,
        pageToken: params.pageToken,
        privateExtendedProperty: params.privateExtendedProperty,
        q: params.q,
        sharedExtendedProperty: params.sharedExtendedProperty,
        showDeleted: params.showDeleted,
        showHiddenInvitations: params.showHiddenInvitations,
        singleEvents: params.singleEvents,
        syncToken: params.syncToken,
        timeMax: params.timeMax,
        timeMin: params.timeMin,
        timeZone: params.timeZone,
        updatedMin: params.updatedMin,
      },
      {
        address: params.address,
        expiration: params.expiration,
        id: params.id,
        kind: params.kind,
        params: params.params,
        payload: params.payload,
        resourceId: params.resourceId,
        token: params.token,
        type: params.type,
      },
      params.signal,
    );
  }

  async delete(params: DeleteEventsInput): Promise<void> {
    return this.client.delete(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
      },
      params.signal,
    );
  }

  async get(params: GetEventsInput): Promise<GetEventsResponse> {
    return this.client.get<GetEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        maxAttendees: params.maxAttendees,
        timeZone: params.timeZone,
      },
      params.signal,
    );
  }

  async patch(params: PatchEventsInput): Promise<PatchEventsResponse> {
    return this.client.patch<PatchEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        conferenceDataVersion: params.conferenceDataVersion,
        maxAttendees: params.maxAttendees,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
        supportsAttachments: params.supportsAttachments,
      },
      {
        anyoneCanAddSelf: params.anyoneCanAddSelf,
        attachments: params.attachments,
        attendees: params.attendees,
        attendeesOmitted: params.attendeesOmitted,
        colorId: params.colorId,
        conferenceData: params.conferenceData,
        description: params.description,
        end: params.end,
        endTimeUnspecified: params.endTimeUnspecified,
        eventType: params.eventType,
        extendedProperties: params.extendedProperties,
        focusTimeProperties: params.focusTimeProperties,
        gadget: params.gadget,
        guestsCanInviteOthers: params.guestsCanInviteOthers,
        guestsCanModify: params.guestsCanModify,
        guestsCanSeeOtherGuests: params.guestsCanSeeOtherGuests,
        iCalUID: params.iCalUID,
        id: params.id,
        location: params.location,
        originalStartTime: params.originalStartTime,
        outOfOfficeProperties: params.outOfOfficeProperties,
        privateCopy: params.privateCopy,
        recurrence: params.recurrence,
        recurringEventId: params.recurringEventId,
        reminders: params.reminders,
        sequence: params.sequence,
        source: params.source,
        start: params.start,
        status: params.status,
        summary: params.summary,
        transparency: params.transparency,
        visibility: params.visibility,
        workingLocationProperties: params.workingLocationProperties,
      },
      params.signal,
    );
  }

  async update(params: UpdateEventsInput): Promise<UpdateEventsResponse> {
    return this.client.put<UpdateEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        conferenceDataVersion: params.conferenceDataVersion,
        maxAttendees: params.maxAttendees,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
        supportsAttachments: params.supportsAttachments,
      },
      {
        anyoneCanAddSelf: params.anyoneCanAddSelf,
        attachments: params.attachments,
        attendees: params.attendees,
        attendeesOmitted: params.attendeesOmitted,
        colorId: params.colorId,
        conferenceData: params.conferenceData,
        description: params.description,
        end: params.end,
        endTimeUnspecified: params.endTimeUnspecified,
        eventType: params.eventType,
        extendedProperties: params.extendedProperties,
        focusTimeProperties: params.focusTimeProperties,
        gadget: params.gadget,
        guestsCanInviteOthers: params.guestsCanInviteOthers,
        guestsCanModify: params.guestsCanModify,
        guestsCanSeeOtherGuests: params.guestsCanSeeOtherGuests,
        iCalUID: params.iCalUID,
        id: params.id,
        location: params.location,
        originalStartTime: params.originalStartTime,
        outOfOfficeProperties: params.outOfOfficeProperties,
        privateCopy: params.privateCopy,
        recurrence: params.recurrence,
        recurringEventId: params.recurringEventId,
        reminders: params.reminders,
        sequence: params.sequence,
        source: params.source,
        start: params.start,
        status: params.status,
        summary: params.summary,
        transparency: params.transparency,
        visibility: params.visibility,
        workingLocationProperties: params.workingLocationProperties,
      },
      params.signal,
    );
  }

  async instances(
    params: InstancesEventsInput,
  ): Promise<InstancesEventsResponse> {
    return this.client.get<InstancesEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}/instances`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        alwaysIncludeEmail: params.alwaysIncludeEmail,
        maxAttendees: params.maxAttendees,
        maxResults: params.maxResults,
        originalStart: params.originalStart,
        pageToken: params.pageToken,
        showDeleted: params.showDeleted,
        timeMax: params.timeMax,
        timeMin: params.timeMin,
        timeZone: params.timeZone,
      },
      params.signal,
    );
  }

  async move(params: MoveEventsInput): Promise<MoveEventsResponse> {
    return this.client.post<MoveEventsResponse>(
      `/calendars/${encodeURIComponent(params.calendarId)}/events/${encodeURIComponent(params.eventId)}/move`,
      {
        alt: params.alt,
        fields: params.fields,
        key: params.key,
        prettyPrint: params.prettyPrint,
        quotaUser: params.quotaUser,
        userIp: params.userIp,
        destination: params.destination,
        sendNotifications: params.sendNotifications,
        sendUpdates: params.sendUpdates,
      },
      undefined,
      params.signal,
    );
  }
}
