/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppThreadRouteImport } from './routes/_app.thread'
import { Route as AppRivetRouteImport } from './routes/_app.rivet'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiRivetSplatRouteImport } from './routes/api/rivet/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadRoute = AppThreadRouteImport.update({
  id: '/thread',
  path: '/thread',
  getParentRoute: () => AppRoute,
} as any)
const AppRivetRoute = AppRivetRouteImport.update({
  id: '/rivet',
  path: '/rivet',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRivetSplatRoute = ApiRivetSplatRouteImport.update({
  id: '/api/rivet/$',
  path: '/api/rivet/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/rivet': typeof AppRivetRoute
  '/thread': typeof AppThreadRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rivet/$': typeof ApiRivetSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inbox': typeof AppInboxRoute
  '/rivet': typeof AppRivetRoute
  '/thread': typeof AppThreadRoute
  '/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rivet/$': typeof ApiRivetSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/rivet': typeof AppRivetRoute
  '/_app/thread': typeof AppThreadRoute
  '/_app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rivet/$': typeof ApiRivetSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inbox'
    | '/rivet'
    | '/thread'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/rivet/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/inbox'
    | '/rivet'
    | '/thread'
    | '/'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/rivet/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/inbox'
    | '/_app/rivet'
    | '/_app/thread'
    | '/_app/'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/rivet/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRivetSplatRoute: typeof ApiRivetSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thread': {
      id: '/_app/thread'
      path: '/thread'
      fullPath: '/thread'
      preLoaderRoute: typeof AppThreadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rivet': {
      id: '/_app/rivet'
      path: '/rivet'
      fullPath: '/rivet'
      preLoaderRoute: typeof AppRivetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rivet/$': {
      id: '/api/rivet/$'
      path: '/api/rivet/$'
      fullPath: '/api/rivet/$'
      preLoaderRoute: typeof ApiRivetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppRivetRoute: typeof AppRivetRoute
  AppThreadRoute: typeof AppThreadRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppRivetRoute: AppRivetRoute,
  AppThreadRoute: AppThreadRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRivetSplatRoute: ApiRivetSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
