export const DURATION_SUGGESTIONS = [
  { label: "15m", value: "15m" },
  { label: "30m", value: "30m" },
  { label: "45m", value: "45m" },
  { label: "1h", value: "1h" },
  { label: "2h", value: "2h" },
  { label: "3h", value: "3h" },
  { label: "4h", value: "4h" },
  { label: "5h", value: "5h" },
  { label: "6h", value: "6h" },
  { label: "7h", value: "7h" },
  { label: "8h", value: "8h" },
  { label: "9h", value: "9h" },
  { label: "10h", value: "10h" },
  { label: "11h", value: "11h" },
  { label: "12h", value: "12h" },
  { label: "13h", value: "13h" },
  { label: "14h", value: "14h" },
  { label: "15h", value: "15h" },
  { label: "16h", value: "16h" },
  { label: "17h", value: "17h" },
  { label: "18h", value: "18h" },
  { label: "19h", value: "19h" },
  { label: "20h", value: "20h" },
  { label: "21h", value: "21h" },
  { label: "22h", value: "22h" },
  { label: "23h", value: "23h" },
  { label: "24h", value: "24h" },
] as const;

export const SUGGESTION_LIMITS = {
  date: 3,
  time: 5,
  duration: 5,
} as const;
